import * as React from "react";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { SafeAuthKit, Web3AuthModalPack } from "@safe-global/auth-kit";
import { OpenloginAdapter } from "@web3auth/openlogin-adapter";
import { type Web3AuthOptions } from "@web3auth/modal";
import { CHAIN_NAMESPACES, WALLET_ADAPTERS } from "@web3auth/base";
/* eslint-disable */
// @ts-nocheck

const options: Web3AuthOptions = {
  clientId: process.env.NEXT_PUBLIC_REACT_APP_WEB3AUTH_CLIENT_ID as string,
  web3AuthNetwork: "testnet",
  chainConfig: {
    chainNamespace: CHAIN_NAMESPACES.EIP155,
    chainId: "0x5", //chainId,
    rpcTarget: `https://rpc.ankr.com/eth_goerli`,
  },
  uiConfig: {
    theme: "dark",
    loginMethodsOrder: ["google", "facebook", "discord"],
  },
};

const modalConfig = {
  [WALLET_ADAPTERS.TORUS_EVM]: {
    label: "torus",
    showOnModal: false,
  },
  [WALLET_ADAPTERS.METAMASK]: {
    label: "metamask",
    showOnDesktop: true,
    showOnMobile: false,
  },
};

const openloginAdapter = new OpenloginAdapter({
  loginSettings: {
    mfaLevel: "mandatory",
  },
  adapterSettings: {
    uxMode: "popup",
    whiteLabel: {
      name: "Safe",
    },
  },
});

const web3AuthModalPack = new Web3AuthModalPack(
  options,
  [openloginAdapter],
  modalConfig
);

// const safeAuthKit = await SafeAuthKit.init(web3AuthModalPack);

// Allow to login and get the derived EOA
// safeAuthKit.signIn();

// // Logout
// safeAuthKit.signOut();

// // Get the provider
// safeAuthKit.getProvider();

let calledInitSafeAuth = false;

const Home: NextPage = () => {
  const [safeAuthKit, setSafeAuthKit] = React.useState<any>(null);

  React.useEffect(() => {
    async function initSafeAuth() {
      if (safeAuthKit == null && calledInitSafeAuth === false) {
        calledInitSafeAuth = true;
        const safeKit = await SafeAuthKit.init(web3AuthModalPack);
        setSafeAuthKit(safeKit);

        const provider = safeKit.getProvider();
        console.log("prv", provider);
        const usrinfo = await safeKit.getUserInfo();
        console.log("usrinfo", usrinfo);
      }
    }
    initSafeAuth();
  });

  console.log(safeAuthKit);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
          </h1>
          <button
            onClick={() => {
              safeAuthKit.signIn();
            }}
          >
            Sign In
          </button>

          <button
            onClick={() => {
              safeAuthKit.signOut();
            }}
          >
            Sign Out
          </button>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">First Steps →</h3>

              <div className="text-lg">
                Just the basics - Everything you need to know to set up your
                database and authentication.
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Documentation →</h3>
              <div className="text-lg">
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
