import React, { useContext } from "react";
import AuthProvider, { AuthContext } from "./authprovider";
import Button from "./button";
import Txt from "./txt";
import Head from "next/head";
import SafeProvider from "@safe-global/safe-apps-react-sdk";

// Define your NavBar component
const NavBar: React.FC = () => {
  const { balance, signIn, signOut, signInResult, userInfo } =
    React.useContext(AuthContext);

  return (
    <nav className=" flex justify-between p-4">
      <div className="flex items-center justify-center gap-2 align-middle">
        <div className="flex-shrink-0">
          <img
            className="h-8 w-8 rounded-full border border-gray-950"
            src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
            alt="Your Company"
          />
        </div>
        <Txt bold>{userInfo?.name}</Txt>
      </div>

      {balance === "N/A" || balance == null ? (
        <Button
          onClick={async () => {
            await signIn();
          }}
        >
          Sign In
        </Button>
      ) : (
        <div className="rounded-3xl bg-black/10 p-2">
          <Txt bold>{balance}</Txt>
        </div>
      )}

      {/* <button
        className="border"
        onClick={async () => {
          await signOut();
        }}
      >
        Sign Out
      </button> */}
    </nav>
  );
};

type LayoutProps = {
  children?: React.ReactNode;
};

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Zilla+Slab:wght@700&display=swap"
          rel="stylesheet"
        ></link>

        <script
          src="https://cdn.ethers.io/lib/ethers-5.2.umd.min.js"
          type="application/javascript"
        ></script>
      </Head>
      <SafeProvider>
        <div className="flex min-h-screen flex-col bg-gradient-color pb-6">
          <NavBar />
          <div className="mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8">
            {children}
          </div>
        </div>
      </SafeProvider>
    </>
  );
};

export default Layout;
